const {chromium}=require('playwright');
const fs=require('node:fs');
const http=require('node:http');
const path=require('node:path');
const assert=require('node:assert/strict');
const root=process.env.SPORTS_TEST_SITE_DIR || '/tmp/gavinwarner-insights';
const artifacts=process.env.SPORTS_TEST_ARTIFACT_DIR || '/tmp/sports-insights-browser';
fs.mkdirSync(artifacts,{recursive:true});
const server=http.createServer((req,res)=>{
 const url=new URL(req.url,'http://localhost');
 let file=path.join(root,decodeURIComponent(url.pathname));
 if(url.pathname.endsWith('/'))file+='index.html';
 fs.readFile(file,(err,data)=>{if(err){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream');res.end(data)});
});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const base=`http://127.0.0.1:${server.address().port}`;
 const browser=await chromium.launch({channel:process.env.SPORTS_TEST_BROWSER || 'msedge',headless:true});
 try {
 const page=await browser.newPage({viewport:{width:1280,height:1000},serviceWorkers:'block'});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const team = (id, abbreviation) => ({id, abbreviation, name: abbreviation, colors:{primary:'#4f2683',secondary:'#fb4f14'}});
 const min=team('min','MIN'), cin=team('cin','CIN');
 const firstStats={targets:9,receptions:8,receiving_yards:92,receiving_tds:2,rushing_yards:-3,rushing_tds:0};
 const secondStats={targets:4,receptions:2,receiving_yards:12,rushing_yards:0,rushing_tds:0};
 const makePlayer=(id,name,team,stats)=>({id,name,position:'WR',seasons:[
   {season:2026,team,stats,weekly_stats:[{week:1,opponent:'GB',stats}]},
   {season:2025,team,stats,weekly_stats:Array.from({length:18},(_,i)=>({week:i+1,opponent:'TB',stats})).filter(w=>w.week!==6)}
 ]});
 const jefferson=makePlayer('00-0036322','Justin Jefferson',min,firstStats);
 const chase=makePlayer('00-0036900',"Ja'Marr Chase",cin,secondStats);
 const defender=makePlayer('defender-player','Test Defender',cin,{def_tackles_solo:4});defender.position='DB';
 const rookie={id:'empty-player',name:'No Stats Player',position:'WR',stats:{},weekly_stats:[],seasons:[]};
 const fixtures={min:{team:min,season:2026,players:[jefferson],injuries:[]},cin:{team:cin,season:2026,players:[chase,defender,rookie],injuries:[]}};
 let failRoster=true;
 await page.addInitScript(()=>{window.drawnText=[];const original=CanvasRenderingContext2D.prototype.fillText;CanvasRenderingContext2D.prototype.fillText=function(text,...args){window.drawnText.push(String(text));return original.call(this,text,...args)};});

 await page.route('**/*',route=>route.request().url().startsWith(base)?route.continue():route.abort());
 await page.route('**/sports/data/teams/*.json',route=>{
   const id=new URL(route.request().url()).pathname.split('/').pop().replace('.json','');
   if(id==='gb' && failRoster){failRoster=false;return route.fulfill({status:503,body:'Unavailable'});}
   return route.fulfill({json:fixtures[id]||{...fixtures.cin,team:team(id,id.toUpperCase())}});
 });
 await page.goto(base+'/sports/player/?team=min&id=00-0036322');
 await page.locator('[data-player-hero]').waitFor({state:'visible'});
 assert.equal(await page.locator('[data-chart-stat]').inputValue(),'receiving_yards');
 assert.equal(await page.locator('.player-chart-bar').count(),1);
 await page.locator('.player-chart-bar').focus();assert.match(await page.locator('[data-chart-summary]').textContent(),/92/);
 await page.selectOption('[data-comparison-team]','cin');
 await page.waitForFunction(()=>!document.querySelector('[data-comparison-group]').disabled);
 assert.deepEqual(await page.locator('[data-comparison-group] option').allTextContents(),['Receivers (1)','Defensive backs (1)']);
 assert.equal(await page.locator('[data-comparison-group]').inputValue(),'receivers');
 assert.equal(await page.locator('[data-comparison-player] option[value="empty-player"]').count(),0);
 assert.equal(await page.locator('[data-comparison-player] option[value="defender-player"]').count(),0);
 await page.selectOption('[data-comparison-group]','defensive-backs');
 assert.equal(await page.locator('[data-comparison-player] option[value="defender-player"]').count(),1);
 await page.selectOption('[data-comparison-group]','receivers');
 await page.locator('[data-comparison-player] option[value="00-0036900"]').waitFor({state:'attached'});
 await page.selectOption('[data-comparison-player]','00-0036900');
 assert.match(await page.locator('[data-comparison-table]').textContent(),/Ja'Marr Chase/);
 assert.match(await page.locator('[data-comparison-table] tbody tr').filter({hasText:'Total yards'}).textContent(),/89.*12/s);
 assert.equal(await page.locator('[data-comparison-share]').isEnabled(),true);
 assert.match(await page.locator('[data-comparison-table] tbody tr').filter({hasText:'Receiving TD'}).textContent(),/—/);
 await page.selectOption('[data-comparison-period]','1');
 await page.click('[data-comparison-share]');
 await page.waitForFunction(()=>document.querySelector('[data-share-status]').textContent.includes('is ready'));
 assert.equal(await page.locator('[data-share-picker] input:checked').count(),4);
 assert.deepEqual(await page.locator('[data-share-options] label').filter({hasText:'Touchdowns'}).allTextContents(),['Touchdowns: 2 / 0']);
 assert.deepEqual(await page.locator('[data-share-options] label').filter({hasText:'Total yards'}).allTextContents(),['Total yards: 89 / 12']);
 assert.equal(await page.locator('[data-share-options] label').filter({hasText:'Receiving TD'}).count(),0);
 assert.equal(await page.locator('[data-share-options] label').filter({hasText:'Rushing TD'}).count(),0);
 const first=page.locator('[data-share-picker] input:checked').first();await first.uncheck();
 await page.locator('[data-share-picker] input:not(:checked):enabled').last().check();
 assert.deepEqual(await page.locator('[data-share-order] strong').allTextContents(),['Receptions','Receiving yards','Touchdowns','Total yards']);
 await page.evaluate(()=>{window.drawnText=[]});
 for(let move=0;move<3;move++)await page.getByRole('button',{name:'Move Total yards up'}).click();
 assert.deepEqual(await page.locator('[data-share-order] strong').allTextContents(),['Total yards','Receptions','Receiving yards','Touchdowns']);
 await page.locator('[data-share-picker]').screenshot({path:path.join(artifacts,'share-order-picker.png')});
 await page.waitForFunction(()=>!document.querySelector('[data-share-download]').disabled);
 assert(await page.evaluate(()=>window.drawnText.lastIndexOf('TOTAL YARDS')<window.drawnText.lastIndexOf('RECEPTIONS')),'Canvas must follow the selected stat order');
 const downloadPromise=page.waitForEvent('download');await page.click('[data-share-download]');
 const download=await downloadPromise;await download.saveAs(path.join(artifacts,'comparison.png'));
 const png=fs.readFileSync(path.join(artifacts,'comparison.png'));assert.equal(png.readUInt32BE(16),1080);assert.equal(png.readUInt32BE(20),1080);
 assert(await page.evaluate(()=>window.drawnText.includes('0')),'Canvas must draw zero values');
 await page.locator('[data-share-canvas]').screenshot({path:path.join(artifacts,'card.png')});
 await page.click('[data-share-close]');
 await page.click('[data-player-season-share]');
 await page.waitForFunction(()=>document.querySelector('[data-share-status]').textContent.includes('is ready'));
 const playerOrderBefore=await page.locator('[data-share-order] strong').allTextContents();
 const playerLast=playerOrderBefore.at(-1);
 await page.getByRole('button',{name:`Move ${playerLast} up`}).click();
 const playerOrderAfter=await page.locator('[data-share-order] strong').allTextContents();
 assert.equal(playerOrderAfter.at(-2),playerLast);
 await page.click('[data-share-close]');
 await page.selectOption('[data-player-season-select]','2025');
 assert.equal(await page.locator('[data-comparison-period]').inputValue(),'season');
 assert((await page.locator('.player-chart-bar').count())>10);
 assert.match(await page.locator('[data-comparison-status]').textContent(),/2025/);
 await page.locator('.player-insights').first().screenshot({path:path.join(artifacts,'chart-desktop.png')});
 await page.locator('[data-chart-details] summary').click();
 await page.locator('.player-insights').first().screenshot({path:path.join(artifacts,'chart-expanded.png')});
 await page.locator('[data-chart-details] summary').click();
 await page.locator('.player-insights').last().screenshot({path:path.join(artifacts,'compare-desktop.png')});
 await page.setViewportSize({width:390,height:844});
 await page.locator('.player-insights').first().screenshot({path:path.join(artifacts,'chart-mobile.png')});
 await page.locator('.player-insights').last().screenshot({path:path.join(artifacts,'compare-mobile.png')});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Page must not overflow on mobile');

 assert.equal(await page.locator('[data-comparison-player] option[value="empty-player"]').count(),0);
 await page.selectOption('[data-comparison-team]','gb');
 await page.locator('[data-comparison-retry]').waitFor({state:'visible'});
 assert(await page.locator('[data-comparison-share]').isDisabled());
 await page.click('[data-comparison-retry]');
 await page.waitForFunction(()=>!document.querySelector('[data-comparison-player]').disabled);
 await page.selectOption('[data-player-season-select]','2026');
 await page.selectOption('[data-chart-stat]','rushing_tds');
 await page.locator('.player-chart-bar').focus();
 assert.match(await page.locator('[data-chart-summary]').textContent(),/0 rushing/);
 await page.selectOption('[data-chart-stat]','rushing_yards');
 await page.locator('.player-chart-bar').focus();
 assert.match(await page.locator('[data-chart-summary]').textContent(),/-3 rushing/);
 assert(Number(await page.locator('.player-chart-bar').getAttribute('height')) > 0);
 await page.goto(base+'/sports/player/?team=cin&id=empty-player');
 await page.locator('[data-player-hero]').waitFor({state:'visible'});
 assert(await page.locator('[data-chart-stat]').isDisabled());
 assert.equal(await page.locator('.player-chart-bar').count(),0);
 assert.match(await page.locator('[data-chart-summary]').textContent(),/once statistics are available/);
 assert.deepEqual(errors,[]);
 console.log('PASS: chart values, cross-team comparison, weekly comparison, stat selection and ordering, PNG export, season changes, mobile overflow, missing seasons, empty data, zero and negative values, roster retry, no page errors');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>server.close());
